# Generated by Django 3.2.9 on 2022-03-31 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Фото')),
                ('deskription', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RegularToure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало тура')),
                ('end', models.DateTimeField(verbose_name='Конец тура')),
                ('places_count', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
                ('status', models.CharField(choices=[('идет набор', 'waiting'), ('Начался', 'start'), ('Завершен', 'completed'), ('Отменен', 'rejected')], default='waiting', max_length=10, verbose_name='Статус')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
            options={
                'verbose_name': 'Регулярный тур',
                'verbose_name_plural': 'Регулярные туры',
                'ordering': ['-start'],
            },
        ),
    ]
